
# mybatis config
mybatis:
  type-aliases-package: com.green.camping-smore
  mapper-locations: classpath:mapper/**/*.xml

# ??? ??? ???? ?? secret key?? ?? HS256 ????? ???? ??, 256???? ????.
# ???? ??? ? 8bit ??? 32?? ???? ??.

spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/team_e_test
    username: root
    password: green502
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


file:
  dir: /home/download/
# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8080

